### ISSUE TITLE
About training process.

### ISSUE THREAD

**Issue by Jamie-Cheung** [mac-mvak/StyleDiffusion#1]
In stylediffusion, the content image and style image are both used in training. But why is only the style image used in your main.py?

**Comment by mac-mvak** [comment]
Hello, I'm very pleased, that you as the author of the paper created an issue in my repo.
I have a hardcoded path to the imagenet dataset, from which I sample pictures. I would like to change it further and add a parameter for a custom path.

I would appreciate it if you as an author of the paper checked the correctness of the losses, which I use in my code, because I might have missed some tricky nuances.
